### ISSUE TITLE
missing last digit of card number

### ISSUE THREAD

**Issue by mattgi** [shatran/card-react#27]
In my Stripe integration tests I use the test number: `4000 0566 5566 5556`.

The number posted to Stripe is `400005665566555`. This number (last 6 missing) still passes the Luhn algorithm so all appears to be fine but the number itself is incorrect.

I believe that, perhaps, this is an issue with the payment library this library depends on.

I am hoping that this is fixed by a not-so-recent [commit](https://github.com/jessepollak/payment/commit/19f58cd26288d308f3e98e052af5eb66ac06b53f) to `payment`.

Therefore, can you upgrade your dependency of `payment` to `2.1.4` and publish a new version?

**Comment by mattgi** [comment]
depending on your desire around dependencies, an alternative option may be to switch to using Stripe's validation methods as per a fork @ https://github.com/thisopenspace/card-react/commit/1f86e88ec3d8b47cb78c96218472154c780a56c1.
Relying on a team rather than an individual for credit card validation may be worthwhile.

**Comment by shatran** [comment]
Hi @mattgi Iv'e just published a version with payment 2.1.6 can you please let me know if this issue is now fixed? thanks.

**Comment by mattgi** [comment]
Hey @shatran,

Bizarrely, no:

`card[number]=400005665566555&card[cvc]=123&card[exp_month]=12&card[exp_year]=2021`

Still missing last digit (i.e. 6) when submitting the data (to Stripe in my instance).

**Comment by mattgi** [comment]
we tracked it down to the introduction of > 16 digit VISA cards not triggering onChange events when the 16th character is entered.. (adds a space, and prevent the change event from firing)... 

As such, the issue is limited to VISAs.. but it does affect every 16 digit VISA card until https://github.com/jessepollak/payment/issues/56 is addressed.

**Comment by stanleycyang** [comment]
I am seeing this as well. You can change `formatting={ false }` to deal with it, however you lose the perks of the card animation
